spring.datasource.url=jdbc:postgresql://localhost:5432/cards_for_interview
spring.datasource.username=cards_user
spring.datasource.password=change_me
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
